### ISSUE TITLE
/rfc crashes site

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#176]
On the current `dev` branch, if you visit `/rfc` it will crash the site with the error below.

This is a fatal error which takes down the entire site.  How can we catch such an exception and recover?

```
'SET_ADVERTISE_CARD_CONTENT'
HTML generation error
ReferenceError: localStorage is not defined
    at Proposals.getAuthorizedUser (/Users/kylepolich/git/dataskeptic.com/shared/Proposals/Routes/Proposals.js:47:22)
    at Proposals.componentWillMount (/Users/kylepolich/git/dataskeptic.com/shared/Proposals/Routes/Proposals.js:34:14)
    at ReactCompositeComponentWrapper.mountComponent (/Users/kylepolich/git/dataskeptic.com/node_modules/react/lib/ReactCompositeComponent.js:210:12)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Users/kylepolich/git/dataskeptic.com/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.mountComponent (/Users/kylepolich/git/dataskeptic.com/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactCompositeComponentWrapper.mountComponent (/Users/kylepolich/git/dataskeptic.com/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Users/kylepolich/git/dataskeptic.com/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.mountComponent (/Users/kylepolich/git/dataskeptic.com/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.mountChildren (/Users/kylepolich/git/dataskeptic.com/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent._createContentMarkup (/Users/kylepolich/git/dataskeptic.com/node_modules/react/lib/ReactDOMComponent.js:591:32)
_http_outgoing.js:542
    throw new TypeError('First argument must be a string or Buffer');
    ^

TypeError: First argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:542:11)
    at writeend (/Users/kylepolich/git/dataskeptic.com/node_modules/express-session/index.js:261:22)
    at Immediate.onsave (/Users/kylepolich/git/dataskeptic.com/node_modules/express-session/index.js:335:11)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dataskeptic.com@1.0.0 dev: `NODE_PATH=$NODE_PATH:./shared babel-node --presets es2015,stage-2 --harmony .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dataskeptic.com@1.0.0 dev script 'NODE_PATH=$NODE_PATH:./shared babel-node --presets es2015,stage-2 --harmony .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dataskeptic.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH=$NODE_PATH:./shared babel-node --presets es2015,stage-2 --harmony .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dataskeptic.com
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dataskeptic.com
npm ERR! There is likely additional logging output above.
```

**Comment by kylepolich** [comment]
@glozhkovoy Got the temporary fix in place.  Thanks for the PR.  But it is an easy mistake to make in coding.  How can we set the site to not do a hard fail if similar issues are introduced in the future?

**Comment by glozhkovoy** [comment]
We plan to have test coverage of core functionality to avoid core issues anymore.
