### ISSUE TITLE
Site does not error out on failed upload

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#187]
If you try to upload a Proposal, it shows the loading screen:

<img width="808" alt="screen shot 2017-08-16 at 12 24 28 am" src="https://user-images.githubusercontent.com/1054674/29351845-55e54db6-8219-11e7-8ce2-74330066694c.png">

But then this error happens:
```
Uploading to s3 /Users/kylepolich/git/dataskeptic.com/recordings/9452bbcd-73a4-4ab6-8632-224cc8ebb681/0.mp3
'dataskeptic-recording'
error
{ AllAccessDisabled: All access to this object has been disabled
    at Request.extractError (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/request.js:684:12)
    at Request.callListeners (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'All access to this object has been disabled',
  code: 'AllAccessDisabled',
  region: null,
  time: 2017-08-16T07:22:28.036Z,
  requestId: 'D5ACE2F1330094A4',
  extendedRequestId: 'OZ5B8iSd9fiCdsRJe4gTLC2fnyQTll4zX7ZiisVkNIcplxSog0zAUwHughxbZGypD83/eNnb1us=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 53.99290879859948 }
```

And no failure is shown to the user.  The wiating screen needs to disappear and give an error message.
<img width="808" alt="screen shot 2017-08-16 at 12 24 28 am" src="https://user-images.githubusercontent.com/1054674/29351838-4e30350e-8219-11e7-81cc-3dfbfdbfd1fe.png">

**Comment by glozhkovoy** [comment]
About error: I think you have problem with S3 Bucket policy. Also I added some error handlers if server is not working
