### ISSUE TITLE
RFC error not clear in UI

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#193]
After submitting an audio recording, I am getting an error (probably an IAM issue)

```
writing in: /Users/kylepolich/git/dataskeptic.com/recordings/8e79d950-42e1-421c-b2b6-ee5ac917f673/0.wav
Uploading to s3 /Users/kylepolich/git/dataskeptic.com/recordings/8e79d950-42e1-421c-b2b6-ee5ac917f673/0.mp3
'dataskeptic-recording'
error
{ AllAccessDisabled: All access to this object has been disabled
    at Request.extractError (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/request.js:684:12)
    at Request.callListeners (/Users/kylepolich/git/dataskeptic.com/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'All access to this object has been disabled',
  code: 'AllAccessDisabled',
  region: null,
  time: 2017-08-19T00:54:57.224Z,
  requestId: 'B03F327D71896293',
  extendedRequestId: 'lAg4ZCyMc6jxzoyvxEhhxzdVQVPShsuPcr710Fda9cVRFn1uLmrKmCJoWSGiGYK0Oqam0mZNtC0=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 43.37502617050828 }
```

But on the front end, it appears to check forever and it never catches the error to report it to the user.

I thought this was fixed, so maybe I have the wrong version or something but I'm on the most updated version of `dev`

![screen shot 2017-08-18 at 5 57 07 pm](https://user-images.githubusercontent.com/1054674/29482050-b427526c-843e-11e7-81cc-53198f233857.png)

**Comment by kylepolich** [comment]
If you want to repeat the error, make the same mistake I did: Set the `aws_proposals_bucket` config value to a non-existent bucket :)

**Comment by kylepolich** [comment]
This issue is about error handling.  When the site administrator (me) correctly configures it, everything is working.  However, if the config is wrong, there should be a more clear error.

You can reproduce the error by putting a fake value in `aws_proposals_bucket`

**Comment by kylepolich** [comment]
Another example of this problem is in #206
