### ISSUE TITLE
Put the ChatBot on all pages

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#569]
Right now, it is only on ContactUs.  There is a feature we built previously for turning the bot on and off.  Please connect these two ideas.  The old version of the bot with the iframe is dead.  We can remove anything to support it.  However, the new bot on Contact Us page should now go on all pages.

**Comment by kylepolich** [comment]
Branch does not compile:

```
kpolich:dataskeptic.com kylepolich$ npm run dev

> dataskeptic.com@1.0.0 dev /Users/kylepolich/git/ds/dataskeptic.com
> NODE_ENV=dev NODE_PATH=$NODE_PATH:./shared babel-node --presets es2015,stage-2 --harmony .

module.js:544
    throw err;
    ^

Error: Cannot find module './msgs.json'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kylepolich/git/ds/dataskeptic.com/shared/Chat/Dialogs/chatter.js:1:20)
    at Module._compile (module.js:641:30)
    at loader (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kylepolich/git/ds/dataskeptic.com/shared/Chat/Dialogs/episodes.js:1:15)
    at Module._compile (module.js:641:30)
    at loader (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/babel-register/lib/node.js:144:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dataskeptic.com@1.0.0 dev: `NODE_ENV=dev NODE_PATH=$NODE_PATH:./shared babel-node --presets es2015,stage-2 --harmony .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dataskeptic.com@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kylepolich/.npm/_logs/2018-03-13T03_08_37_565Z-debug.log
```

**Comment by gleblozhkovoy** [comment]
Have no this error. Lets investigate during the call
