### ISSUE TITLE
careers_cityname branch is broken

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/dataskeptic.com#689]
I get this error:

```
server.jsx : updateState for /podcast
using cache for contributors
get_podcasts_from_cache
server.jsx : updateState for /careers/city/chicago
using cache for contributors
No images found! Can't build the thumb list without images. If you don't need thumbs, set showThumbs={false} in the Carousel. Note that it's not possible to get images rendered inside custom components. More info at https://github.com/leandrowd/react-responsive-carousel/blob/master/TROUBLESHOOTING.md
HTML generation error
TypeError: Cannot read property 'map' of null
    at Thumbs.renderItems (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react-responsive-carousel/lib/components/Thumbs.js:279:38)
    at Thumbs.render (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react-responsive-carousel/lib/components/Thumbs.js:358:30)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactPerf.js:66:21)
    at ReactCompositeComponentWrapper.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.mountChildren (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent._createContentMarkup (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactDOMComponent.js:591:32)
(node:10238) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): The first argument must be one of type string or Buffer
```

The site ends up in a very bad state after this.  Nothing works.

**Comment by gliblozhkovyi** [comment]
I have merged this branch with `dev` and got an empty response for cities like`Boston` and `Chicago.`

@jing9932 Could you check that routes for `dev` environment when you will have time? Maybe that's issue from my side, but I haven't changed the elastic search endpoint URL
